name: Documentation

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Publish Jazzy Docs
      uses: Steven0351/publish-jazzy-docs@v1.1.0
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
